services:
  etna-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: etna-app-container
    volumes:
      - ./results:/app/results
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    restart: on-failure
